# -*- coding: utf-8 -*-
"""math program.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1LJyASHrnSuDQeth8MD9GjVt6puGNJWbI
"""

m=float(input('Enter the mass fo object : '))
v=float(input('Enter the valume of object : '))
Density=m/v
print(Density)

"""Fgrav = (Gm1m2)/d2"""

G=9.81
m1=float(input('enter the Mass of 1st object'))
m2=float(input('Enter the mass of 2nd object'))
d=float(input('Enter the distance of two object'))
Force=G*(m1*m2)/(d*d)
print(Force)

y1=int(input('enter the slope of y1 : '))
y2=int(input('enter the slope of y2 : '))

x1=int(input('enter the slope of x1 : '))
x2=int(input('enter the slope of x2 : '))
slope=(y2-y1)/(x2-x1)
print(slope)
y=y1-slope*x1
print(y)

"""d = √[(
x
2
 − 
x
1
)2 + (
y
2
 − 
y
1
)2]
"""

import math
point_x1=int(input('enter the value of x1 : '))
point_x2=int(input('enter the value of x2 : '))

point_y1=int(input('enter the value of y1 : '))
point_y2=int(input('enter the value of y2 : '))

squre_root= math.sqrt(((x2-x1)**2)+((y2-y1)**2))
print(squre_root)

num=4+2.1j
num.real

z=complex(1,2)
print(z)

import math
rea=int(input('Enter the real num : '))
imag=int(input('Enter the real imag : '))

modulus=math.sqrt((rea)**2+(imag)**2)
print(modulus)

num=complex(rea,imag)
print(num)

import math
z=complex (input('Enter the complex number : '))
a=z.real
b=z.imag

modulus=math.sqrt((a)**2+(b)**2)
print(modulus)
print(z)

"""x = [-b ± √(b2 - 4ac)]/2a"""

import cmath
a=int(input('enter the value of a : '))
b=int(input('enter the value of b : '))
c=int(input('enter the value of c : '))

d=(b**2)-(4*a*c)
root1=-b-cmath.sqrt((d)/(2*a))
root2=-b+cmath.sqrt((d)/(2*a))
print(root1)
print(root2)

"""3x2+4x−5=0

"""

#Quadratic equation

import math
num=int(input('enter the number : '))
result=math.sqrt(num**2)
print(result)

import cmath
a=int(input('Enter the value of a : '))
b=int(input('Enter th value of b : '))
c=int(input('Enter the value of c : '))
root1=(b**2)-(4*a*c)
p_root=-b+cmath.sqrt(root1)/(2*a)

root2=(b**2)-(4*a*c)
n_root=-b-cmath.sqrt(root2)/(2*a)
print(p_root)
print(n_root)

"""K = C + 273.15"""

Celsius=float(input('Enter the temp into celsius : '))
Kelvin=Celsius+273.15
print(Kelvin)

"""
C = K − 273.15"""

kelvin=int(input('Enter the temp in the kelvin : '))
celsius=kelvin-273.15
print(celsius)